import { getProducts, getConfig, load, save, getOrders, saveOrders, money } from '../assets/js/store.js';import { KEYS } from '../assets/js/config.js';
const login=document.querySelector('#adminLogin');const panel=document.querySelector('#adminPanel');
function authenticated(){return sessionStorage.getItem(KEYS.adminSession)==='ok';}
function showPanel(){login.hidden=true;panel.hidden=false;renderAll();}
if(authenticated())showPanel();
document.querySelector('#loginForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(d.email==='admin@velmora.local'&&d.password==='velmora2026'){sessionStorage.setItem(KEYS.adminSession,'ok');showPanel();}else document.querySelector('#loginError').hidden=false;});
document.querySelector('#logoutAdmin').addEventListener('click',()=>{sessionStorage.removeItem(KEYS.adminSession);location.reload();});

document.querySelectorAll('[data-admin-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-admin-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.admin-view').forEach(v=>v.hidden=true);document.querySelector(`#${b.dataset.adminTab}`).hidden=false;}));
function renderAll(){renderDashboard();renderProducts();renderOrders();renderCustomers();renderCoupons();renderSettings();}
function renderDashboard(){const products=getProducts(),orders=getOrders();document.querySelector('#metricProducts').textContent=products.length;document.querySelector('#metricStock').textContent=products.reduce((s,p)=>s+Number(p.stock||0),0);document.querySelector('#metricOrders').textContent=orders.length;document.querySelector('#metricRevenue').textContent=money.format(orders.reduce((s,o)=>s+Number(o.total||0),0));document.querySelector('#lowStock').innerHTML=products.filter(p=>Number(p.stock)<=Number(p.minimumStock)).slice(0,8).map(p=>`<li><span>${p.brand} ${p.name}</span><strong>${p.stock} un.</strong></li>`).join('')||'<li>Nenhum alerta.</li>';}
function renderProducts(){const tbody=document.querySelector('#adminProductsBody');tbody.innerHTML=getProducts().map(p=>`<tr><td>${p.sku}</td><td><strong>${p.name}</strong><small>${p.brand}</small></td><td><input type="number" step="0.01" data-field="price" data-product="${p.id}" value="${p.price??''}" placeholder="0,00"></td><td><input type="number" data-field="stock" data-product="${p.id}" value="${p.stock??0}"></td><td><input data-field="image" data-product="${p.id}" value="${p.image??''}" placeholder="assets/products/arquivo.webp"></td><td><button class="small-button" data-save-product="${p.id}">Salvar</button></td></tr>`).join('');}
document.addEventListener('click',e=>{const saveButton=e.target.closest('[data-save-product]');if(saveButton){const id=saveButton.dataset.saveProduct;const overrides=load(KEYS.productOverrides,{});overrides[id]=overrides[id]||{};document.querySelectorAll(`[data-product="${id}"]`).forEach(input=>{overrides[id][input.dataset.field]=input.dataset.field==='image'?input.value:(input.value===''?null:Number(input.value));});save(KEYS.productOverrides,overrides);saveButton.textContent='Salvo';setTimeout(()=>saveButton.textContent='Salvar',1200);renderDashboard();}const status=e.target.closest('[data-order-status]');if(status){const orders=getOrders();const order=orders.find(o=>o.id===status.dataset.orderStatus);if(order){order.status=status.value;saveOrders(orders);renderOrders();}}});
function renderOrders(){const orders=getOrders();document.querySelector('#adminOrdersBody').innerHTML=orders.length?orders.map(o=>`<tr><td>${o.id}</td><td>${new Date(o.createdAt).toLocaleDateString('pt-BR')}</td><td>${o.name||'—'}</td><td>${money.format(o.total||0)}</td><td><select data-order-status="${o.id}">${['Aguardando confirmação','Pagamento aprovado','Separando pedido','Enviado','Entregue','Cancelado'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join(''):'<tr><td colspan="5">Nenhum pedido local registrado.</td></tr>';}
function renderCustomers(){const map=new Map();getOrders().forEach(o=>{const key=o.whatsapp||o.email||o.name;if(!key)return;const c=map.get(key)||{name:o.name,whatsapp:o.whatsapp,email:o.email,orders:0,total:0};c.orders++;c.total+=Number(o.total||0);map.set(key,c);});document.querySelector('#adminCustomersBody').innerHTML=[...map.values()].map(c=>`<tr><td>${c.name||'—'}</td><td>${c.whatsapp||'—'}</td><td>${c.email||'—'}</td><td>${c.orders}</td><td>${money.format(c.total)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum cliente registrado.</td></tr>';}
function renderCoupons(){const coupons=load(KEYS.coupons,[]);document.querySelector('#couponList').innerHTML=coupons.map((c,i)=>`<li><strong>${c.code}</strong><span>${c.type==='percent'?c.value+'%':money.format(c.value)}</span><button data-delete-coupon="${i}">Excluir</button></li>`).join('')||'<li>Nenhum cupom.</li>';}
document.querySelector('#couponForm').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const coupons=load(KEYS.coupons,[]);coupons.push({...data,value:Number(data.value)});save(KEYS.coupons,coupons);e.target.reset();renderCoupons();});document.addEventListener('click',e=>{const d=e.target.closest('[data-delete-coupon]');if(d){const coupons=load(KEYS.coupons,[]);coupons.splice(Number(d.dataset.deleteCoupon),1);save(KEYS.coupons,coupons);renderCoupons();}});
function renderSettings(){const config=getConfig();const f=document.querySelector('#settingsForm');Object.entries(config).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??'';});}
document.querySelector('#settingsForm').addEventListener('submit',e=>{e.preventDefault();save(KEYS.settings,Object.fromEntries(new FormData(e.target)));document.querySelector('#settingsSaved').hidden=false;setTimeout(()=>document.querySelector('#settingsSaved').hidden=true,2000);});
